wisdom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth.decorators import login_required

from registration.views import SignUpView, UserActivationView, EmailConfirmationView
from auditory.views import HomeView, audio_upload, success, AuditoriumView

urlpatterns = [
    # Admin
    path('admin/', admin.site.urls),
    # Registration app
    path('', include("django.contrib.auth.urls")),
    path('', login_required(HomeView.as_view())),
    path('signup/', SignUpView.as_view(), name="signup"),
    path('email_confirmation/', EmailConfirmationView.as_view(), name="email_confirmation"),
    path('activate/<uidb64>/<token>/', UserActivationView.as_view(), name="activate"),
    # Auditory app
    path('home/', HomeView.as_view(), name="home"),
    path('upload/', audio_upload, name='upload'),
    path('success/', success, name='success'),
    path('auditorium/<str:id>', AuditoriumView.as_view(), name="auditorium"),
]

# Add media storage paths
if settings.DEBUG is True:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

# Error pages
handler403 = "wisdom.views.handle_403"
handler404 = "wisdom.views.handle_404"
handler500 = "wisdom.views.handle_500"

auditory/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
import logging
import uuid
import mutagen

from .validators import validate_file_extension, validate_file_size


logger = logging.getLogger(__name__)


class Audio(models.Model):
    uuid = models.UUIDField(
        primary_key=True,
        unique=True,
        default=uuid.uuid4,
        editable=False,
    )
    name = models.CharField(
        max_length=50,
        blank=False,
        null=True,
    )
    description = models.CharField(
        max_length=200,
        blank=True,
        null=True,
    )
    thumbnail = models.ImageField(
        upload_to="thumbnail",
        null=True,
    )
    audiofile = models.FileField(
        upload_to='audio',
        validators=[
            validate_file_extension,
            validate_file_size,
        ]
    )
    author = models.CharField(
        max_length=30,
        blank=True,
        null=True,
        default="Not Available",
    )
    duration = models.IntegerField(
        blank=True,
        null=True,
        default=1
    )
    uploaded = models.DateTimeField(
        auto_now_add=True,
        editable=False,
        blank=False,
        null=True,
    )

    def __str__(self):
        return self.name


@receiver(pre_save, sender=Audio)
def audio_duration_reader(sender, instance, **kwargs):
    """Update auido duration value before saving audio object"""
    try:
        # Read audio file metadata
        audio_info = mutagen.File(instance.audiofile).info

        # Update audio duration field value
        instance.duration = int(audio_info.length)

    except Exception as e:
        logger.exception(e)


@receiver(post_delete, sender=Audio)
def audio_post_delete_handler(sender, **kwargs):
    """Delete audio and thumbnail files on object deletion"""
    try:
        # Get Audio instance
        audio = kwargs["instance"]

        # Get path and name of audio and thumbnail files
        audio_storage, audio_name = audio.audiofile.storage, audio.audiofile.name
        thumbnail_storage, thumbnail_name = audio.thumbnail.storage, audio.thumbnail.name

        # Delete files in storage
        audio_storage.delete(audio_name)
        thumbnail_storage.delete(thumbnail_name)

    except Exception as e:
        logging.exception(e)

auditory/forms.py
from django import forms

from .models import Audio


# Custom design of form inputs
widget_name = forms.TextInput(attrs={
    "class": "input is-info mb-5",
    "placeholder": "Audio title"
})
widget_description = forms.Textarea(attrs={
    "class": "textarea is-info mb-5",
    "placeholder": "Description",
    "rows": 4
})
widget_thumbnail = forms.ClearableFileInput(attrs={'class': 'mb-5'})
widget_audiofile = forms.ClearableFileInput(attrs={'class': 'mb-5'})
widget_author = forms.TextInput(attrs={
    "class": "input is-info mb-5",
    "placeholder": "Author",
})


class UploadFileForm(forms.ModelForm):
    """File upload form with custom styling"""
    name = forms.CharField(label="", widget=widget_name)
    description = forms.CharField(label="", widget=widget_description)
    author = forms.CharField(label="", widget=widget_author)

    class Meta:
        model = Audio
        fields = ("name", "description", "thumbnail", "audiofile", "author")
        widgets = {
            "thumbnail": widget_thumbnail,
            "audiofile": widget_audiofile,
        }

auditory/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView

from .models import Audio
from .forms import UploadFileForm


class HomeView(ListView):
    template_name = "home.html"
    model = Audio


class AuditoriumView(ListView):
    template_name = "auditorium.html"
    model = Audio

    def get_queryset(self):
        """Filter audio object by audio id"""
        return Audio.objects.filter(uuid=self.kwargs["id"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["other_audios"] = Audio.objects.exclude(uuid=self.kwargs["id"]).all()
        # Prevent passing over 10 audios
        if len(context["other_audios"]) > 10:
            context["other_audios"] = context["other_audios"][:10]
        return context


def audio_upload(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)

        if form.is_valid():
            form.save()
            return redirect('success')
    else:
        form = UploadFileForm()

    # returns form to template
    return render(
        request,
        'upload.html',
        {'form': form}
    )


def success(request):
    return render(request, "upload_success.html")

wisdom/views.py
from django.shortcuts import render


def handle_403(request, exception):
    return render(request, "error_403.html", context={}, status=403)


def handle_404(request, exception):
    return render(request, "error_404.html", context={}, status=404)


def handle_500(request):
    return render(request, "error_500.html", context={}, status=500)

auditory/templates/_contents_list.html
<div class="section has-background-white">
  <p class="subtitle is-3">Audio Contents</p>
  <div class="columns is-multiline">
    {% for audio in audio_list %}
    <div class="column">
      <div class="card m-3">
        <a href="{% url 'auditorium' id=audio.uuid %}" style="color: inherit">
          <div class="card-image">
            <figure class="image is-4by3">
              <img
                src="https://s3-ap-southeast-2.amazonaws.com/wisdom-storage/{{ audio.thumbnail }}"
                alt="Image"
              />
            </figure>
          </div>
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                {% if audio.name|length <= 30 %}
                <p class="title is-4">{{ audio.name }}</p>
                {% else %}
                <p class="title is-4">{{ audio.name|slice:27 }}...</p>
                {% endif %}
                {% if audio.description|length <= 100 %}
                <p class="sub-title is-4">{{ audio.description }}</p>
                {% else %}
                <p class="sub-title is-4">{{ audio.description|slice:97 }}...</p>
                {% endif %}
              </div>
            </div>
            <div class="content">
              <small>{{ audio.author }}</small><br />
              <small>{{ audio.duration }} sec</small><br />
              <small>{{ audio.uploaded }}</small>
            </div>
          </div>
        </a>
      </div>
    </div>
    {% empty %}
    <p>Sorry no audio is available at the moment...</p>
    {% endfor %}
  </div>
</div>

auditory/templates/_personality.html
<a class="button is-primary" href="/upload">
  <span>UPLOAD AUDIO</span>
</a>

auditory/templates/auditorium.html
{% extends "base.html" %}
{% block main %}
<!-- Audio -->
<div class="column has-text-centered is-7">
  {% for audio in audio_list %}
  <!-- Player -->
  <div class="media p-3 audio-meta">
    <div class="media-left">
      <figure class="image is-128x128">
        <img
          src="https://s3-ap-southeast-2.amazonaws.com/wisdom-storage/{{ audio.thumbnail }}"
          alt="Image"
        />
      </figure>
    </div>
    <div class="media-content p-2 m-2 has-background-white">
      <h2 class="title">{{ audio.name }}</h2>
      <p class="is-size-6">By: {{ audio.author }}</p>
      <p class="is-size-6">{{ audio.uploaded }}</p>
    </div>
  </div>
  <div>
    <audio controls class="audio-player">
      <source
        src="https://s3-ap-southeast-2.amazonaws.com/wisdom-storage/{{ audio.audiofile }}"
        type="audio/mpeg"
      />
    </audio>
  </div>
  <!-- Description -->
  <div class="notification has-background-white">
    <p class="subtitle is-5">Description</p>
    <hr>
    <p>{{ audio.description }}</p>
  </div>
  {% empty %}
  <p>Selected audio not found...</p>
  {% endfor %}
</div>
<!-- Recommendations -->
<div class="column is-3 p-3 recommended">
  <div>
    <h3 class="subtitle">RECOMMENDED AUDIOS</h3>
  </div>
  <hr>
  {% for other_audio in other_audios %}
  <a href="{% url 'auditorium' id=other_audio.uuid %}">
    <article class="media">
      <div class="media-left">
        <figure class="image is-48x48">
          <img
            src="https://s3-ap-southeast-2.amazonaws.com/wisdom-storage/{{ other_audio.thumbnail }}"
            alt="Image"
          />
        </figure>
      </div>
      <div class="media-content">
        <p class="subtitle is-5">{{ other_audio.name }}</p>
        <p class="subtitle is-7">{{ other_audio.author }}</p>
        <p class="subtitle is-7">{{ other_audio.uploaded }}</p>
      </div>
    </article>
  </a>
  <hr>
  {% empty %}
  <p>No other audios available...</p>
  {% endfor %}
  </div>
</div>
{% endblock %}

auditory/templates/home.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-10">
<h1 class="title">Welcome to WISDOM!</h1>
{% include '_personality.html' %}
{% include '_contents_list.html' %}
</div>
{% endblock %}

auditory/templates/index.html
{% extends "base.html" %}
{% block main %}
<h1 class="title">Welcome to WISDOM!</h1>
{% include '_personality.html' %}
{% include '_contents_list.html' %}
{% endblock %}

auditory/templates/upload.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-half">
  <form class="column is-three-fifths is-offset-one-fifth" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="button is-info" type="submit">Upload</button>
  </form>
</div>
{% endblock %}

auditory/templates/upload_success.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-half">
  <h1 class="title">Upload successful!</h1>
  <p class="button is-light"><a href="{% url 'home' %}">Back to Home</a></p>
</div>
{% endblock %}

templates/_footer.html
<footer class="footer">
  <div class="container">
    <div class="content has-text-centered">
      <p>WISDOM by ht-90</p>
      <a class="icon is-medium fas fa-2x" href="https://github.com/ht-90/wisdom" target="_blank">
        <span class="icon has-text-dark">
          <i class="fab fa-github"></i>
        </span>
      </a>
      <p>Copyright©{% now "Y" %}</p>
    </div>
  </div>
</footer>

templates/_navbar.html
<nav class="navbar is-info">
  <div class="navbar-brand">
    <a class="navbar-item title is-4" href="/">WISDOM</a>
  </div>
  <div class="navbar-end">
    {% if not user.is_authenticated %}
    <a class="navbar-item" href="{% url 'signup' %}">Sign Up</a>
    <a class="navbar-item" href="{% url 'login' %}">Log In</a>
    {% else %}
    <a class="navbar-item" href="{% url 'logout' %}">Log Out</a>
    {% endif %}
  </div>
</nav>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css"
    />
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" />
    <link
      href="https://unpkg.com/@fortawesome/fontawesome-free@5.13.0/css/all.css"
      rel="stylesheet"
    />
  </head>
  <body>
    {% include '_navbar.html' %}
    <section class="section">
      <div class="container">
        <div class="columns is-centered">
          {% block main %}
          <p>No Content Here ;;</p>
          {% endblock %}
        </div>
      </div>
    </section>
    {% include '_footer.html' %}
  </body>
</html>

templates/error_403.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-half">
  <h1 class="title">Sorry, the requested page is not allowed to access...</h1>
</div>
{% endblock %}

templates/error_404.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-half">
  <h1 class="title">Sorry, the requested page not found in WISDOM...</h1>
</div>
{% endblock %}

templates/error_500.html
{% extends "base.html" %}
{% block main %}
<div class="column has-text-centered is-half">
  <h1 class="title">There was an issue with server...</h1>
</div>
{% endblock %}